# Generated by Django 4.2.5 on 2024-04-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0003_order'),
        ('pens', '0003_order_orderitem_order_products_order_user'),
    ]

    operations = [
    ]
