# Generated by Django 4.2.5 on 2024-05-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0003_order_product_reorder_level_and_more'),
        ('pens', '0004_merge_20240412_1145'),
    ]

    operations = [
    ]
