# Generated by Django 4.2.5 on 2024-05-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0007_refillrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pens.supplier'),
        ),
    ]
