# Generated by Django 4.2.5 on 2024-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0008_alter_refillrequest_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refillrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='refillrequest',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
